#include <stdio.h>
#include <stdlib.h>
#include <tiledb/tiledb.h>

#define ERR_CHCK(stat) { if (stat != TILEDB_OK) { printf("TileDB Error Code: %d\n", stat); return -1; } }

int main() {
    // Must match the array folder name generated by the conversion code
    const char* tiledb_array_name = "muscal_tiledb";

    tiledb_ctx_t* ctx;
    tiledb_ctx_alloc(NULL, &ctx);

    tiledb_array_t* array;
    tiledb_array_alloc(ctx, tiledb_array_name, &array);
    if (tiledb_array_open(ctx, array, TILEDB_READ) != TILEDB_OK) {
        fprintf(stderr, "Error opening TileDB array. Does '%s' exist?\n", tiledb_array_name);
        return -1;
    }

    // Variables to track metadata types and element counts
    tiledb_datatype_t type;
    uint32_t num_depth, num_lat, num_lon;
    const void* value_ptr;

    // 1. Inspect metadata entries to verify sizing from storage headers
    ERR_CHCK(tiledb_array_get_metadata(ctx, array, "coords_depth", &type, &num_depth, &value_ptr));
    ERR_CHCK(tiledb_array_get_metadata(ctx, array, "coords_latitude", &type, &num_lat, &value_ptr));
    ERR_CHCK(tiledb_array_get_metadata(ctx, array, "coords_longitude", &type, &num_lon, &value_ptr));

    printf("Found Coordinate Arrays in Metadata:\n");
    printf(" - Depths: %u elements\n", num_depth);
    printf(" - Latitudes: %u elements\n", num_lat);
    printf(" - Longitudes: %u elements\n\n", num_lon);

    // 2. Allocate heap memory for your local application buffers
    float* depth_vals = (float*)malloc(num_depth * sizeof(float));
    float* lat_vals   = (float*)malloc(num_lat * sizeof(float));
    float* lon_vals   = (float*)malloc(num_lon * sizeof(float));

    if (!depth_vals || !lat_vals || !lon_vals) {
        fprintf(stderr, "Allocation failed for reading arrays.\n");
        return -1;
    }

    // 3. Extract the arrays from TileDB into our allocated buffers via typecasting the value_ptr
    int i;
    
    ERR_CHCK(tiledb_array_get_metadata(ctx, array, "coords_depth", &type, &num_depth, &value_ptr));
    float* depth_ptr = (float*)value_ptr;
    for(i = 0; i < (int)num_depth; i++) depth_vals[i] = depth_ptr[i];

    ERR_CHCK(tiledb_array_get_metadata(ctx, array, "coords_latitude", &type, &num_lat, &value_ptr));
    float* lat_ptr = (float*)value_ptr;
    for(i = 0; i < (int)num_lat; i++) lat_vals[i] = lat_ptr[i];

    ERR_CHCK(tiledb_array_get_metadata(ctx, array, "coords_longitude", &type, &num_lon, &value_ptr));
    float* lon_ptr = (float*)value_ptr;
    for(i = 0; i < (int)num_lon; i++) lon_vals[i] = lon_ptr[i];

    // --- SANITY CHECK: Print sample data values ---
    printf("=== Real-World Coordinate Sample (First 3) ===\n");
    printf("Depth Values     : %f, %f, %f\n", depth_vals[0], depth_vals[1], depth_vals[2]);
    printf("Latitude Values  : %f, %f, %f\n", lat_vals[0], lat_vals[1], lat_vals[2]);
    printf("Longitude Values : %f, %f, %f\n", lon_vals[0], lon_vals[1], lon_vals[2]);

    // Clean up allocated memory blocks
    free(depth_vals);
    free(lat_vals);
    free(lon_vals);

    // Close connections cleanly
    tiledb_array_close(ctx, array);
    tiledb_array_free(&array);
    tiledb_ctx_free(&ctx);

    return 0;
}

